name: Build and push main image

on:
  push:
    tags:
      - '*'

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: "build"
        run: npm run build
