name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: "build"
        run: |
          npm run build
          ls -a
