name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: "build"
        run: |
          npm install
          npm run build
          zip -r dist.zip dist 
          gh release create ${{ github.run_number }}.0.0 dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
        shell: bash
        
